### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by brouberol** [thomas-maurice/puppet-as-a-service-wrapper#2]
Here is a list of _suggestions_ to improve the overall UX with the package:
- Add docstrings (at least to the classes)
- Document the `__getattr__` hack with a docstring, as it could be useful for potential unexpected hacks (ie: bidouilles, not black hat stuff)
- Rename `api_client` to `client` (simple and shorter) 
- Make the package pip installable by adding a `setup.py`, and pushing it to PyPI.

I'd be happy to help with these, especially with PyPI: It's a PITA to do if you first have to look for documentation (often obsolete), and I've done it a lot.

**Comment by thomas-maurice** [comment]
WIP in progress :D

**Comment by thomas-maurice** [comment]
Issues partially addressed in https://github.com/thomas-maurice/puppet-as-a-service-wrapper/pull/3

Still lacks the pypi packaging though

**Comment by thomas-maurice** [comment]
Fixed in commit e37c51a4e7937637d34efa5a4cc2b27bdd4293e8 :)

Now deployed to pypi
